languageCode = 'en-us'
baseurl = 'https://nacelle.dev'
title = 'Nacelle'
disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    style = "github"
    lineNos = true
    noClasses = true

[params]
  author = 'Eric Fritz'
  dateformat = '01/02/2006'
  index_page = '/landing'
  resources_root = 'https://assets.nacelle.dev'
  categories = ['quickstart', 'core', 'frameworks', 'base processes', 'libraries']

[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]