languageCode = 'en-us'
baseurl = 'https://nacelle.dev'
title = 'Nacelle'
disableKinds = ['taxonomy', 'taxonomyTerm', 'RSS']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = 'Eric Fritz'
  dateformat = '01/02/2006'
  index_page = '/landing'
  resources_root = 'https://assets.nacelle.dev'
  categories = ['core', 'frameworks', 'base processes', 'libraries']

[params.highlight]
  languages = ['go', 'dockerfile']
