version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12.7.0-stretch
    working_directory: ~/website
  go:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/website

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run:
          name: Download hugo
          command: |
            version="0.62.2"
            curl -L -o hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${version}/hugo_${version}_Linux-64bit.tar.gz"
            tar -xvzf hugo.tar.gz hugo
            sudo mv hugo /usr/local/bin/hugo
            rm hugo.tar.gz
      - run: hugo
      - run: npm run minify
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - public
            - bin

  deploy:
    executor: go
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: go run ./dev/deploy.go
      - run:
          name: Bust cache
          command: go run ./dev/bust-cache.go

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
