version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.7.0-stretch
    working_directory: ~/website
    steps:
      - checkout
      - run: npm install
      - run:
        command: |
          curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.56.1/hugo_0.56.1_Linux-64bit.tar.gz
          tar -xvzf hugo.tar.gz hugo
          rm hugo.tar.gz
      - run: hugo
      - run: npm run minify

  deploy:
    docker:
      - image: alpine:3.8
    working_directory: ~/website
    steps:
      - run: ./bin/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
