version: 2.1

commands:
  update_docs:
    description: Synchronize the nacelle documentation website with a recently updated README.
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: Clone repository
          command: |
            git clone https://${GITHUB_TOKEN}@github.com/go-nacelle/website.git
      - run:
          name: Synchronize documentation
          command: |
            cd website
            ./bin/sync-repos.sh "<< parameters.repo >>"

            # If nothing changed, early out the rest of the job
            if [[ -z $(git diff) ]]; then circleci step halt; fi
      - run:
          name: Download hub binary
          command: |
            version="2.12.3"
            dir="hub-linux-amd64-$version"

            # Download hub utility and put it in PATH
            curl -L -o hub.tar.gz "https://github.com/github/hub/releases/download/v${version}/${dir}.tgz"
            tar -xvzf hub.tar.gz "${dir}/bin/hub"
            sudo mv "${dir}/bin/hub" /usr/local/bin/hub
            rm -rf hub.tar.gz ${dir}
      - run:
          name: Submit pull request
          command: |
            git config --global user.name "Eric Fritz"
            git config --global user.email "eric@eric-fritz.com"

            branch="sync-<< parameters.repo >>-${CIRCLE_SHA1:0:6}"
            message="Sync documentation from go-nacelle/<< parameters.repo >>."

            cd website

            # Don't make a PR unless it would create a new branch and commit
            if [[ -z $(git ls-remote --heads https://github.com/go-nacelle/website "${branch}") ]]; then
              git checkout -b "${branch}"
              git commit -am "${message}"
              git push origin "${branch}"
              hub pull-request -m "${message}"
            fi
